// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID        int64     `json:"id"`
	User      string    `json:"user"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	Upvotes   int64     `json:"upvotes"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	Karma             int64     `json:"karma"`
}
