// Code generated by sqlc. DO NOT EDIT.
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    "user",
    title,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, "user", title, content, created_at, upvotes
`

type CreatePostParams struct {
	User    string `json:"user"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.User, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, "user", title, content, created_at, upvotes FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, "user", title, content, created_at, upvotes FROM posts
ORDER BY id
LIMIT $1
`

func (q *Queries) ListPosts(ctx context.Context, limit int32) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.Upvotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
