// Code generated by sqlc. DO NOT EDIT.
// source: post.sql

package db

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    "user",
    title,
    content,
    "subreddit"
) VALUES (
    $1, $2, $3, $4
) RETURNING id, "user", title, content, subreddit, created_at, upvotes
`

type CreatePostParams struct {
	User      string `json:"user"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Subreddit string `json:"subreddit"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.User,
		arg.Title,
		arg.Content,
		arg.Subreddit,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.Subreddit,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :one
DELETE FROM posts
WHERE id = $1
RETURNING id, "user", title, content, subreddit, created_at, upvotes
`

func (q *Queries) DeletePost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, deletePost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.Subreddit,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, "user", title, content, subreddit, created_at, upvotes FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.Subreddit,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, "user", title, content, subreddit, created_at, upvotes FROM posts
WHERE subreddit = $1
ORDER BY id
LIMIT $2
`

type ListPostsParams struct {
	Subreddit string `json:"subreddit"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Subreddit, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Title,
			&i.Content,
			&i.Subreddit,
			&i.CreatedAt,
			&i.Upvotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $1, content = $2
WHERE id = $3
RETURNING id, "user", title, content, subreddit, created_at, upvotes
`

type UpdatePostParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost, arg.Title, arg.Content, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Title,
		&i.Content,
		&i.Subreddit,
		&i.CreatedAt,
		&i.Upvotes,
	)
	return i, err
}
